Fix delete memory error
Significant-Gravitas/Auto-GPT pull request #105
Opened 2023-04-03 21:03 UTC by ryanmac

delete_memory made consistent with overwrite_memory, preventing the error:

```
Command memory_del returned: Error: '>=' not supported between instances of 'str' and 'int'
```

2023-04-03 21:22 UTC, JamesFincher submitted a review, later dismissed
Looks great. Simple fix too!

2023-04-05 19:27 UTC, jmagly approved these changes
this is working, thank you!

2023-04-09 10:29 UTC, nponeccop requested changes
Remove the gitignore change from this PR.

2023-04-09 10:29 UTC, nponeccop commented on .gitignore
An unrelated change. Should be submitted as a separte PR

2023-04-09 16:03 UTC, jmagly commented
does this pr even make sense if memory is using pinecone now? these were all hacks we were throwing in to fix issues with file loading.

2023-04-10 08:45 UTC, nponeccop commented
@ryanmac Remove the unrelated changes and resolve the conflicts.

2023-04-15 21:29 UTC, BillSchumacher commented
The functions this fixes were removed already, closing.

2023-04-15 21:29 UTC, closed without merging