add openai api base support
Significant-Gravitas/Auto-GPT pull request #1097
Opened 2023-04-13 12:10 UTC by cnych

### Background
In some scenarios, it is not possible to directly access the official OpenAI API address. It is necessary to access it through a proxy address, which can be specified by specifying env `OPENAI_API_BASE`.

### Changes
Added an `OPENAI_API_BASE` environment variable to configure the base URL of the OpenAI API.

### Documentation

### Test Plan

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

2023-04-13 12:34 UTC, nponeccop submitted a review, later dismissed
OPENAI_API_BASE is never used

2023-04-13 12:41 UTC, cnych commented
> OPENAI_API_BASE is never used

You can override the default `https://api.openai.com/v1` by configuring `OPENAI_API_BASE` in `.env`.

This is very much needed for scenarios where direct access to the OpenAI API is not possible.

2023-04-13 13:26 UTC, zsjinwei submitted a review, later dismissed
test pass

2023-04-13 13:26 UTC, cryptidv commented
> > It's not actually used when making API requests.
> > Additionally, wouldn't this violate OpenAI's TOS? If you can't access OAI's APIs either due to geoblocking or some other reason, can't you just use a VPN (or even Azure)?
> 
> In fact, the OpenAI SDK itself provides a direct configuration entry for `openai.api_base`. For example, you can use Cloudflare Worker service to proxy the OpenAI API and perform related statistics at the Cloudflare level.

Ah I see ok! LGTM then 👍

2023-04-13 19:40 UTC, nponeccop commented
@cnych There are conflicts now

2023-04-15 02:05 UTC, cnych commented
> @cnych There are conflicts now

The conflict has been resolved.

2023-04-15 09:40 UTC, nponeccop commented
@cnych We decided to do another major cleanup, so that the code is very tidy. It will be ready later today so I'll notify when it's time to fix conflicts again. And, if you happen to speak Chinese, can you join our discussion in #1508 ?

2023-04-15 13:24 UTC, cnych commented
> @cnych We decided to do another major cleanup, so that the code is very tidy. It will be ready later today so I'll notify when it's time to fix conflicts again. And, if you happen to speak Chinese, can you join our discussion in #1508 ?

Ok！I'm Chinese! I'll take a look at your discussion.

2023-04-15 14:06 UTC, nponeccop commented
@cnych Thanks. There are conflicts now.

2023-04-16 13:31 UTC, gaye746560359 commented
> 

如何设置？我试了在。env文件添加OPENAI_API_BASE=https://sssssss/v1并没有效果

2023-04-16 13:39 UTC, cnych commented
> > 
> 
> 如何设置？我试了在。env文件添加OPENAI_API_BASE=[https://sssssss/v1并没有效果](https://sssssss/v1%E5%B9%B6%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C)

You need add `openai.api_base = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1")` to `config.py`.

2023-04-16 13:49 UTC, gaye746560359 commented
> > > 
> > 
> > 
> > 如何设置？我试了在。env文件添加OPENAI_API_BASE=[https://sssssss/v1并没有效果](https://sssssss/v1%E5%B9%B6%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C)
> 
> You need add `openai.api_base = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1")` to `config.py`.

有效，非常感谢

2023-04-17 11:55 UTC, nponeccop commented
@cnych There are conflicts now

2023-04-17 13:02 UTC, cnych commented
> @cnych There are conflicts now

Oh... could you merge this PR first? The update is too fast now, I have resolved four or five conflicts～

2023-04-18 20:27 UTC, nponeccop requested changes

2023-04-18 20:27 UTC, nponeccop commented on requirements-docker.txt
This looks unrelated. Revert.

2023-04-20 06:41 UTC, sweetlilmre commented
Hi. Suggest closing this PR in favour of #2594 which adds broader functionality

2023-04-20 06:48 UTC, closed without merging