Add Bing Search functionality and update README
Significant-Gravitas/Auto-GPT pull request #1170
Opened 2023-04-13 18:55 UTC by ForestLinSen

### Background
This pull request aims to enhance the search capabilities of the application by adding Bing Search functionality as an alternative to Google Search. Users can now choose between Google and Bing as their preferred search engine by specifying the --bing flag when running the program. This change aligns with the project's goal of providing versatile and user-friendly tools for information retrieval.

### Changes
1. Implemented the bing_search function to support Bing Search API integration.
2. Modified the execute_command function to accept a search_engine parameter, allowing for seamless integration of additional search engines in the future.
3. Updated the README.md file with clear instructions on how to enable Bing Search and set up Azure API keys for Bing Search support.

### Documentation
In-code comments have been added to explain the new bing_search function and the modifications made to the execute_command function. The README.md file has been updated to provide detailed instructions on enabling Bing Search and setting up Azure API keys, making it easy for users to understand and utilize the new feature.

### Test Plan
Tested the Bing Search functionality with various prompts to ensure accurate search results.
Verified that the --bing flag works as intended, allowing users to switch between Google and Bing as their search engine.
Ensured that the application continues to work as expected when no search engine flag is specified (defaults to Google Search).

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

2023-04-13 19:11 UTC, nponeccop submitted a review, later dismissed

2023-04-14 10:57 UTC, nponeccop requested changes

2023-04-14 10:57 UTC, nponeccop commented on scripts/main.py
> +    main()
There is whitespace error here. Press Enter once after main(). It won't pass the linter anyway.

2023-04-14 10:57 UTC, nponeccop commented on scripts/main.py
> -from prompt import get_prompt
While you are at it, revert this change as well as unrelated. You can submit it as a separate PR. We are happy to merge one-liners.

2023-04-14 11:38 UTC, Artemonim commented
Why didn't you change and use `.env.template`?

2023-04-14 11:56 UTC, ForestLinSen commented
> Why didn't you change and use `.env.template`?

Thank you for your suggestion! I have updated the .env.template file to include the AZURE_API_KEY variable

2023-04-14 11:58 UTC, Artemonim commented
> > Why didn't you change and use `.env.template`?
> 
> Thank you for your suggestion! I have updated the .env.template file to include the AZURE_API_KEY variable

I've mean `SEARCH_ENGINE=your-choice`

2023-04-14 12:06 UTC, nponeccop approved these changes

2023-04-14 22:50 UTC, ForestLinSen commented
@nponeccop Hi! just want to update that I have resolved the conflicts and broken code that were introduced by the module introduction

2023-04-14 22:53 UTC, nponeccop approved these changes

2023-04-15 13:26 UTC, nponeccop commented
@ForestLinSen There are conflicts now

2023-04-15 17:11 UTC, nponeccop requested changes
There are conflicts

2023-04-15 20:19 UTC, ForestLinSen commented
> There are conflicts

Hi @nponeccop , the conflicts are resolved now

2023-04-16 15:16 UTC, nponeccop approved these changes

2023-04-16 15:17 UTC, nponeccop approved these changes

2023-04-16 16:29 UTC, nponeccop commented
@richbeales @p-i- Can you provide the author with some guidance as for the planned plugins feature?

2023-04-20 09:58 UTC, closed without merging

2023-04-20 20:11 UTC, ForestLinSen commented
Hi @nponeccop , I refactored the code as a plugin following this template: https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template. Should I modify and reopen the pull request here, create a new one, or follow any other guidance?

2023-05-19 22:14 UTC, ForestLinSen commented
> Is this feature still engaging? Or is it abandoned?

Hi, this function has been integrated into the first-party plugins, you can find more information here: https://github.com/Significant-Gravitas/Auto-GPT-Plugins/tree/master