Use selenium for web browsing
Significant-Gravitas/Auto-GPT pull request #121
Opened 2023-04-03 23:25 UTC by Agusx1211

- Allows for browsing dynamic pages (Twitter, Google, .etc).
- It lets the agent read the whole page (paginated view)
- - Resuming can be added back later, but I think this performs better
- I added "No images" to the base prompt, otherwise it tries to fetch images.
- Selenium can later be used to further interact with the page (click buttons, fill forms).

2023-04-04 02:05 UTC, Durafen commented
The AI appears to like paging and reading more detailed websites, however, I think there should be an option to obtain a get_text_summary of the whole webpage via prompt.

2023-04-04 10:01 UTC, Torantulino commented
@Agusx1211 Could you please resubmit this as an optional (using an argument) rather than replacing the existing code?

There have been some good improvements to browsing since this was submitted, but we're still looking for a major solution.

2023-04-04 10:28 UTC, Agusx1211 commented
I can't work on this until late night. What do you mean as an optional? like adding a flag that changes the behavior?

2023-04-04 12:28 UTC, developerisnow commented
> I can't work on this until late night. What do you mean as an optional? like adding a flag that changes the behavior?

Yes, looks like he meant this. Cause it's major improvement which needs separate flag

2023-04-05 00:37 UTC, ryanmac commented
See also PR https://github.com/Torantulino/Auto-GPT/pull/96 which uses Playwright instead of requests.

But I also second the request that this is triggered by an argument.

2023-04-06 06:55 UTC, sberney commented
I think this should be an alternate kind of command that the AI can run if the default (static) beautifulsoup parser fails.

2023-04-09 10:48 UTC, nponeccop commented
An important thing is that Selenium makes it harder to setup. And it somehow assumes that Chrome is the only Selenium web driver. So, for it to merge I guess (I'm not the maintainer) it should be an entirely optional feature with a separate document describing the installation, keeping the current "for dummies" installation procedure as is.

2023-04-09 10:49 UTC, nponeccop requested changes
LGTM except the Chrome driver hardcoding. Support at least Firefox and Edge as well both in code and instructions.

And rebase against the current master.

2023-04-10 13:28 UTC, nponeccop requested changes
Resolve the conflicts and split the prompt changes.

2023-04-10 13:28 UTC, nponeccop commented on scripts/data/prompt.txt
Separate the prompt changes into a different PR.

2023-04-15 21:14 UTC, richbeales commented
Selenium is now in the master branch

2023-04-15 21:14 UTC, closed without merging