beggining to add docstrings to file_operations
Significant-Gravitas/Auto-GPT pull request #1234
Opened 2023-04-14 03:24 UTC by j00x

### Background

### Changes

### Documentation

### Test Plan

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-04-14 06:17 UTC, nponeccop requested changes

2023-04-14 06:17 UTC, nponeccop commented on scripts/file_operations.py
> -# Set a dedicated folder for file I/O
This change doesn't look like it adds docstrings. Keep it atomic

2023-04-14 06:17 UTC, nponeccop commented on scripts/main.py
> -               speak.say_text("Apparently json was fixed.")
Revert this whitespace change too, unless requested by the linter.

2023-04-14 06:17 UTC, nponeccop commented on scripts/memory/__init__.py
> -def get_memory(cfg, init=False):
Unrelated changes again. Not docstrings. Submit in a separate PR

2023-04-14 06:17 UTC, nponeccop commented on scripts/memory/base.py
> +class MemoryProviderSingleton(AbstractSingleton):
Class introduction is unrelated to adding docstrings. Separate PR

2023-04-14 06:17 UTC, nponeccop commented on scripts/memory/local.py
I guess you get the idea by now

2023-05-05 00:57 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-06-14 23:00 UTC, closed without merging