Add integration test for code execution
Significant-Gravitas/Auto-GPT pull request #1268
Opened 2023-04-14 07:34 UTC by rickythefox

### Background
There is no integration test for code execution using docker.

### Changes
Added integration test.

### Documentation
N/A

### Test Plan
Ran the test and it passed.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

2023-04-27 18:52 UTC, Pwuts requested changes

2023-04-27 18:52 UTC, Pwuts commented on tests/integration/execute_code_test.py
Please rename this to `test_execute_code.py`, and rewrite using `pytest` instead of `unittest`

2023-04-27 21:16 UTC, rickythefox commented on tests/integration/execute_code_test.py
Done, glad to use pytest instead.

2023-04-27 21:17 UTC, Pwuts commented on tests/integration/test_execute_code.py
> +import autogpt.commands.execute_code as sut
sut?

2023-04-27 21:18 UTC, rickythefox commented on tests/integration/test_execute_code.py
> +import autogpt.commands.execute_code as sut
Subject Under Test.

2023-04-28 12:49 UTC, Pwuts approved these changes
Made a few additions

2023-04-28 12:51 UTC, merged