feat: add shell access to auto-gpt command loop
Significant-Gravitas/Auto-GPT pull request #135
Opened 2023-04-04 02:31 UTC by esgoode

Update prompt to give shell access and add shell execution command

2023-04-04 02:37 UTC, prestoj commented
This is a good idea, but also dangerous. When Python files are executed by Auto-GPT, it is done in an isolated container to alleviate the potential for, e.g., rm -rfucking your machine. I think the better solution is to spin up a docker container and give Auto-GPT access to it rather than giving it direct shell access to your machine.

2023-04-04 09:26 UTC, Torantulino commented
Absolutely agreed @prestoj.

It sounds great but we need to make this one safe to use.

2023-04-04 14:57 UTC, ryanpeach commented
I think we should stick to one primary language. Almost everything you can do in shell can already be done in the python executor.

2023-04-04 23:01 UTC, dschonholtz commented
> I think we should stick to one primary language. Almost everything you can do in shell can already be done in the python executor.

Although this is technically true, if you want an agent that can actually self improve, it needs to be able to run shell commands in a container to be able to pull down git repos and interact with a github CLI etc. 
Not to mention rapid status checking and multi-process management. 

All of that is possible in python, but the vast majority of the commands in GPT-4's training data will be run in bash. I think this should be considered essential with respect to getting the agent to self improve. 

I would really like to see an eventual pipeline of:
Github issue on kanban gets assigned to AutoGPT, which triggers CI/CD to stand up an AutoGPT instance in the cloud in a ubuntu container, which in turn clones the repo, reads the associated issue, reproduces it, interacts with the github CLI, and then pushes a PR.

To do that series of steps, we really need it to be able to interact with git and python through a shell not purely through the python interpreter.

2023-04-09 10:58 UTC, nponeccop approved these changes
LGTM code-wise. However this is a dangerous optional feature. But something like this we need, although in a more specialized way, e.g. an ability to git log. It's also important that it doesn't break the current Windows compatibility so it's accessible to more people. As an optional feature it's ok.

2023-04-10 08:51 UTC, nponeccop commented
@esgoode Resolve the conflicts

2023-04-10 13:32 UTC, nponeccop requested changes

2023-04-10 13:32 UTC, nponeccop commented on scripts/data.py
> +        return ""
Revert this change

2023-04-10 13:32 UTC, nponeccop commented on scripts/execute_code.py
> +        return f"Error: {str(e)}"
Add the trailing line separator

2023-04-12 11:23 UTC, xg1990 commented
How about we disable it by default and users can choose to enable it at their own risk?
Otherwise I would still apply this code patch in my local version anyway.
Or shall we make it an optional extension that users can choose to install?

2023-04-15 22:36 UTC, BillSchumacher commented
This is resolved with the execute_shell command. Which wouldn't break if it was already inside a docker container, closing.

2023-04-15 22:36 UTC, closed without merging