Image generation improvements
Significant-Gravitas/Auto-GPT pull request #1477
Opened 2023-04-15 05:08 UTC by Tymec

### Background

[AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) exposes an API for generating images using it. This feature can be useful for cutting down costs for generating images and allowing flexibility and more power for tweaking image generation. 
By using the API exposed by [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui), we can generate images more efficiently and flexibly. This feature allows us to reduce the costs of image generation and to customize the image generation parameters for different models and settings.

### Changes

- Added support for using [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) API as an image provider
- Renamed "sd" image provider to "huggingface" to avoid confusion
- Added config options to change HuggingFace text-to-image model, image size, image count and SD WebUI settings
- Modified the `generate_image` function to accept arguments for prompt, negative prompt, num_images, image_size, model and extra params

### Documentation

- The code changes are documented using docstrings and comments

### Test Plan

- Created a unit test module for image generation to test each image provider

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-04-15 05:12 UTC, Tymec commented
I'm not sure whether adding the huggingface image model option breaks the atomicity of this pull request, so if there's any issues with that, please let me know.

2023-04-15 07:04 UTC, nponeccop submitted a review, later dismissed

2023-04-16 15:45 UTC, nponeccop submitted a review, later dismissed

2023-04-16 15:46 UTC, nponeccop commented
@Tymec There are conflicts now

2023-04-16 17:26 UTC, nponeccop commented
@Tymec CI is red

2023-04-18 19:58 UTC, nponeccop requested changes
Remove unrelated changes (not only those few I highlighted)

2023-04-18 19:58 UTC, nponeccop commented on .gitignore
Is it related? If not revert

2023-04-18 19:58 UTC, nponeccop commented on .pre-commit-config.yaml
Clearly unrelated

2023-04-18 19:58 UTC, nponeccop commented on autogpt/__main__.py
> +    prompt = construct_prompt()
Variable renaming isn't related to image generation improvements either

2023-04-19 00:29 UTC, BillSchumacher approved these changes

2023-04-19 00:29 UTC, merged