Teaches Auto-GPT to use DB connection and SQL execution
Significant-Gravitas/Auto-GPT pull request #166
Opened 2023-04-04 11:24 UTC by KaneCohen

Adds new flag `--db` which tells Auto-GPT to try and establish connection with common mysql-like databases and then perform couple of basic functions:

- Reading information about specific table
- Based on table data create and execute SQL created a given user request

Beware of little Bobby Tables.

2023-04-05 11:29 UTC, ZsoltGergely approved these changes

2023-04-09 11:35 UTC, nponeccop requested changes

2023-04-09 11:35 UTC, nponeccop commented on scripts/commands.py
> -
Submit the whitespace fixes in a separate PR

2023-04-09 11:35 UTC, nponeccop commented on scripts/json_parser.py
> -        return "failed"
Note that this is also a whitespace fix

2023-04-10 09:02 UTC, nponeccop commented
@KaneCohen Resolve the conflicts and make the PR more focused

2023-04-10 11:56 UTC, nponeccop requested changes

2023-04-10 11:56 UTC, nponeccop commented on scripts/commands.py
> +
Unrelated whitespace change

2023-04-10 11:56 UTC, nponeccop commented on scripts/config.py
> +
More whitespace

2023-04-10 11:56 UTC, nponeccop commented on scripts/main.py
> +
Too many blank lines

2023-04-10 11:57 UTC, nponeccop commented
There are conflicts again :-\

2023-04-10 12:04 UTC, nponeccop commented
Well, I don't know how to review it, the "condensed view" confuses me. @ryanpeach ?

2023-04-11 16:38 UTC, nponeccop commented
@KaneCohen Can you resolve the conflicts?

2023-04-11 17:28 UTC, nponeccop approved these changes
Good job. Now a few whitespace fixes.

2023-04-11 17:28 UTC, nponeccop commented on .env.template
> +
Remove the extra empty line

2023-04-11 17:28 UTC, nponeccop commented on scripts/config.py
> +
Here too. Don't reformat the code you don't change

2023-04-11 17:28 UTC, nponeccop commented on scripts/main.py
> +
Two empty lines is enough. Remove the third one.

2023-04-26 18:16 UTC, Wladastic commented
Was this abandoned?

2023-04-27 00:41 UTC, KaneCohen commented
> Was this abandoned?

Hey, given the rate of change on a main repo - seemed like a good idea to let it stabilise first.

2023-04-27 00:51 UTC, ntindle commented
This would be a great plug-in!

2023-04-27 06:15 UTC, ntindle commented
Hello!  We sincerely appreciate your contribution to our project. We encourage you to open a pull request in the Auto-GPT-Plugins repository.  If you encounter any difficulties in converting your code into a plugin, please do not hesitate to seek assistance from the #plugins-chat on our Discord Server.  We look forward to your contribution to the Plugins repository and apologize for any inconvenience this may have caused.

2023-04-27 06:16 UTC, closed without merging