Run AutoGPT without GUI
Significant-Gravitas/Auto-GPT pull request #1670
Opened 2023-04-15 18:32 UTC by Zep4yrWang

### Background

### Changes

Now supports running selenium without GUI, enabling running on terminal-only machines. 

### Documentation

### Test Plan

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-04-16 04:56 UTC, SargeDGz commented
my work around was to install a desktop environment and rdp in and then run autogpt but yea rdp over internet is bad, thanks for this hope it gets merged in to the project.

2023-04-16 14:28 UTC, yudikubota commented
I tried running it and got the following error:

![image](https://user-images.githubusercontent.com/22172999/232319827-6792018d-bc0c-4ad6-9661-f5a38f0a3202.png)

2023-04-16 18:28 UTC, Zep4yrWang commented
> I tried running it and got the following error:
> 
> ![image](https://user-images.githubusercontent.com/22172999/232319827-6792018d-bc0c-4ad6-9661-f5a38f0a3202.png)

Hi. 'master' branch is being updated very frequently and sometimes requirements.txt falls behind. Manual installation will solve this. 
`pip install GitPython`

2023-04-18 03:14 UTC, stellarkey reviewed
A good solution to non-GUI-able environments!

2023-04-18 03:14 UTC, stellarkey approved these changes
I think it's approvable.

2023-04-18 03:17 UTC, stellarkey requested changes

2023-04-18 03:17 UTC, stellarkey commented on autogpt/config/config.py
> +        self.no_gui=False
please make it `self.no_gui = False`

2023-05-05 00:57 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-05-05 05:38 UTC, anonhostpi commented
Recommend building an asynchronous API to talk to the currently running process would be the best method.

Some kind of IPC. I'm sure there are several IPC libraries for Python. Another option would be to host a local http server that takes REST/GRAPHQL calls.

2023-05-05 10:37 UTC, Boostrix commented
especially once multiple async agents are becoming a thing (#765, #2422), this will be highly useful

2023-06-15 00:43 UTC, Pwuts commented
Since #1473+#2816, browsers open in headless mode by default. This can be adjusted using an environment variable or the `.env` config, which is probably enough for now. Still, thanks for submitting!

2023-06-15 00:43 UTC, closed without merging