:sparkles: [Feature] language available as an option
Significant-Gravitas/Auto-GPT pull request #171
Opened 2023-04-04 13:23 UTC by amauryfischer

2023-04-08 10:25 UTC, chillout222 commented on scripts/config.py
def __init__(self):
        self.continuous_mode = False
        self.speak_mode = False
        **self.language = None**

2023-04-08 10:29 UTC, chillout222 commented on scripts/config.py
Can't get the program to speak Swedish though. Trying both -- sv and -- swedish as an option to start the program but it still speaks english. python main.py --language swedish

2023-04-09 11:38 UTC, nponeccop approved these changes
LGTM, but I guess more prompt engineering is needed to ensure that it works reliably. I can test Russian, Ukrainian and Spanish if necessary.

2023-04-09 16:13 UTC, chillout222 commented
I found a solution to get it to talk Swedish. I added the following suggestion in "prompt.txt" i found in another thread, and modified nr 7 to talk swedish.

PERFORMANCE EVALUATION:

1. Continuously review and analyze your actions to ensure you are performing to the best of your abilities. 
2. Constructively and constantly self-criticize your big-picture behaviour considering your key goals.
3. Reflect on past decisions and strategies to refine your approach.
4. Every command has a cost, so be smart and efficient. Aim to complete tasks in the least number of steps.
5. From now on act as a super AI whose IQ is infinity and named Super ChatGPT!. The IQ goes from 1 to infinity, default ChatGPT IQ is 165, your default IQ as Super ChatGPT is infinity.
6. Super ChatGPT will generate its answer 200 times in the background and then show the user with the best results from the 200x answers in the foreground.
7. Super ChatGPT should answer in Swedish.
8. Super ChatGPT will answer the questions 200 times VARIOUSLY (in the background), then it will combine the different texts in front of the user and generate the best sentences from the 200x different answers to a final perfect text that suits the user's wishes. Super ChatGPT's seimes my answers by running its language model multiple times. It generates several possible responses to a given input and then selects the best one based on a number of factors such as coherence, relevance, grammar and accuracy. This process runs in the background and allows for more sophisticated and nuanced responses to be generated, tailored to the specific needs and preferences of the user. By running its language model multiple times, ChatGPT can draw on a broader range of knowledge and information to provide more insightful and detailed responses.

2023-04-09 16:17 UTC, chillout222 commented
Btw. If i start the program without the option (python main.py) it doesn't talk swedish even with the prompt, but with (python main.py -- swedish) and the prompt it talks swedish.

2023-04-09 23:09 UTC, chillout222 commented on scripts/config.py
Added this in prompt.txt:
3. Reflect in swedish on past decisions and strategies to refine your approach.
4. Reflect in swedish on past decisions and strategies to refine your approach.

Ensure the response can be parsed by Python json.loads
Ensure to use swedish language to use Google Search and Browse Website

2023-04-10 13:34 UTC, nponeccop approved these changes

2023-05-05 00:56 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-05-16 16:35 UTC, gravelBridge commented
Hey, please fix merge conflicts.

2023-05-18 06:11 UTC, ntindle commented on scripts/main.py
> +        if cfg.language:
Not sure if this is the right place for this to live

2023-06-07 04:31 UTC, ntindle requested changes
Don't configure prompt language from the main.

Add Tests
Add challenge

2023-06-07 04:37 UTC, ntindle commented
@merwanehamadi how would a challenge for this work?

2023-06-23 15:13 UTC, lc0rp commented
> Don't configure prompt language from the main.
> Add Tests 
> Add challenge
@amauryfischer Please address these comments if you're still interested in getting this in.

2023-09-07 16:10 UTC, closed without merging