Integrated Twilio
Significant-Gravitas/Auto-GPT pull request #1735
Opened 2023-04-15 22:57 UTC by CatsMeow492

Background
In order to receive notifications from the AutoGPT application via SMS, a new feature has been implemented. This feature uses the Twilio API to send text messages to a specified phone number.

Changes
Added a new Python script that sends SMS messages using the Twilio API.
Implemented a function send_sms(to, body) that sends a text message to a given phone number with the specified message body.
Configured the script to use environment variables stored in a .env file for sensitive information (Twilio Account SID, Auth Token, and phone number).
Documentation
The new Python script includes in-code comments explaining the purpose of each section, how to set up the Twilio API, and how to use the send_sms() function in the application.

Test Plan
Set up a Twilio account and obtain the necessary credentials (Account SID, Auth Token, and phone number).
Install the Twilio Python library and python-dotenv library.
Create a .env file containing the Twilio credentials.
Implement the send_sms() function in the Python script.
Test the script by calling the send_sms() function with a valid recipient phone number and message body.
Verify that the text message is received by the recipient.
PR Quality Checklist
 My pull request is atomic and focuses on a single change.
 I have thoroughly tested my changes with multiple different prompts.
 I have considered potential risks and mitigations for my changes.
 I have documented my changes clearly and comprehensively.
 I have not snuck in any "extra" small tweaks changes.
By submitting this, I agree that my pull request should be closed if I do not fill this out or follow the guidelines.

2023-04-16 14:56 UTC, nponeccop approved these changes

2023-04-16 14:57 UTC, nponeccop commented
@CatsMeow492 There are conflicts now

2023-04-17 11:40 UTC, nponeccop requested changes

2023-04-17 11:40 UTC, nponeccop commented on autogpt/commands/send_text.py
> +    recipient = '+11234567890'
This doesn't look right

2023-04-17 11:44 UTC, nponeccop commented
And CI is red

2023-04-22 23:36 UTC, ntindle commented
This would fit better in the plugins repo! https://github.com/Significant-Gravitas/Auto-GPT-Plugins

2023-04-22 23:36 UTC, closed without merging