Main
Significant-Gravitas/Auto-GPT pull request #1741
Opened 2023-04-15 23:34 UTC by royalrick

### Background

1. For areas where Google is blocked, a proxy is needed to access Google.

2. Third-party vendors similar to [API2D](https://api2d.com) have emerged for Openai's interface, and their interfaces may be more suitable for certain regions. If you want to use their interface, you need to replace Openai's restricted address.

### Changes

1. add environment variables 'HTTP_PROXY_HOST' and 'HTTP_PROXY_PORT'  for http proxy.
2. add environment variable 'OPENAI_API_BASE' for custom Openai api's base address.

### Documentation

### Test Plan

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

2023-04-16 05:20 UTC, richbeales commented
please re-title

2023-04-16 15:03 UTC, nponeccop submitted a review, later dismissed

2023-04-16 15:03 UTC, nponeccop commented on .env.template
> +HTTP_PROXY_PORT=7890
The final newline is missing

2023-04-16 15:29 UTC, royalrick commented on .env.template
> +HTTP_PROXY_PORT=7890
already resolved.

2023-04-17 01:15 UTC, nponeccop requested changes
Change the PR title to something meaningful as requested by @richbeales

2023-04-17 01:24 UTC, royalrick commented
> Change the PR title to something meaningful as requested by @richbeales

OK

2023-04-17 01:34 UTC, nponeccop submitted a review, later dismissed

2023-04-17 01:35 UTC, nponeccop commented
@richbeales He fixed

2023-05-05 00:54 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-07-07 06:43 UTC, Pwuts commented
Thanks for submitting! This PR may be old, but it's not unmergeable.

A few remarks though:
* Implementing measures to circumvent internet blockages is not within Auto-GPT's scope.
* The possibility to set custom API base URLs was added with #2594 

That doesn't really leave anything still to be merged in this PR. Still, feel free to join our discord and weigh in, discuss or join in on the action there! Useful contributions are always welcome, even if we sometimes take a while to review & merge. :)

2023-07-07 06:43 UTC, closed without merging