Teach Docker to Auto-GPT
Significant-Gravitas/Auto-GPT pull request #181
Opened 2023-04-04 14:58 UTC by finaldzn

Work in progress, but im Trying to give auto gpt a way to build, manage, and run command inside docker containers.

The goal are : 
- No need tp set up any dev environnment for Auto-Gpt to work
- A way for Auto-GPT to run any commands in a controlled environnement
- A way for Auto-GPT to develop complete apps using the virtual docker environment.

Im not sure about : 
- The prompts given to explain the commands
- The goal i gave auto gpt

Here is the reference goal with wich i've tried : 

Any suggestions is welcomed

```
ai_goals:
- set up a dev environnement for a react app using docker
- 'create a new bare react app '
- add a component to the react app that shows the current time
- run the app, access it and print in a file the html
ai_name: Developer-GPT
ai_role: Set up working coding a environment and then follow user instructions to
  create an app
```

2023-04-05 13:55 UTC, st4s1k commented on scripts/docker_test.py
shouldn't a test assert something?
at least print out the result of an equals operation

2023-04-09 11:42 UTC, nponeccop requested changes

2023-04-09 11:42 UTC, nponeccop commented on scripts/commands.py
> -
Submit the whitespace fixes as a separate PR, to keep the diff here small.

2023-04-10 09:05 UTC, nponeccop commented
@finaldzn Now it's outdated. Resolve the conflicts and make it more focused

2023-04-20 17:20 UTC, AndresCdo commented
@finaldzn Resolve the conflicts.

2023-04-20 17:21 UTC, AndresCdo commented on scripts/commands.py
> +
Delete whitespace.

2023-04-20 17:21 UTC, AndresCdo commented on scripts/commands.py
> +
Delete whitespace.

2023-05-05 00:56 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-06-14 22:24 UTC, Pwuts commented
Closing this PR because no activity in the past 2 months. Interesting idea though; I have labeled it with `fridge` so we can find it back and use it as inspiration later, when the dust of re-arch settles. Or if you want, feel free to rebase your changes on current `master` and resubmit :)

2023-06-14 22:24 UTC, closed without merging