Fix DevToolsActivePort file doesn't exist for headless machine VM/Docker
Significant-Gravitas/Auto-GPT pull request #1849
Opened 2023-04-16 11:08 UTC by nathtest

### Background
The command browse_website always returned: Error: Message: unknown error: DevToolsActivePort file doesn't exist on my VM.
It looks like sometime the port of Chrome is used by another process so changing port helps fixing the error.

Headless machine also require to run chrome in headless mode.

### Changes
Modify the selenium driver option to work in headless mode.

### Documentation
Added comments on what the option do.

### Test Plan

Running autogpt with headless=new and changing the port of -remote-debugging-port to something else than default fixed the error.
I tested it on numerous browse_website commands that now ran with success.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes.

2023-04-16 15:37 UTC, nponeccop submitted a review, later dismissed

2023-04-17 00:55 UTC, nponeccop requested changes
Apparently there are many unrelated changes. You need to revert them.

2023-04-17 00:55 UTC, nponeccop commented on .env.template
> +# TEMPERATURE - Sets temperature in OpenAI (Default: 0)
This change doesn't look right

2023-04-17 00:55 UTC, nponeccop commented on .github/workflows/ci.yml
This is also an unrelated change that creeped in during auto-merge

2023-04-17 17:40 UTC, closed without merging

2023-04-17 18:06 UTC, nathtest commented
will redo this correctly