Fix for: write_to_file 'PosixPath' object has no attribute 'is_relative_to' (python3.8 )
Significant-Gravitas/Auto-GPT pull request #2474
Opened 2023-04-19 01:36 UTC by primaryobjects

### Background

- This is a fix for the write_to_file command error.
https://github.com/Significant-Gravitas/Auto-GPT/issues/2027

### Changes

- Added backwards compatibility check for `is_relative_to` and `relative_to` to use correct method depending on version of python 3.8 versus 3.10, 3.11+.

### Documentation

No config required by user.

### Test Plan

- Tested locally.
- Unit tested with python3.8 and python3.11.

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes.

2023-04-19 02:43 UTC, collijk requested changes
Here's the thing: `safe_path_join` is only ever used in the function calling above.  And just by sort of the guarantees of python's pathlib `my_path = base_path.joinpath(*other_paths)` implies (in the mathematical sense) that `my_path.is_relative_to(base_path)`.  So this condition tests nothing. The error is unreachable.

2023-04-19 02:43 UTC, collijk commented on autogpt/workspace.py
> +    ) or not joined_path.relative_to(base)
`path_a.relative_to(path_b)` is not a boolean statement.  It makes a new path in the form `path_a / path_b`.  This does not do quite what you want, therefore.

2023-04-19 02:47 UTC, collijk commented
The correct resolution, I think, is to delete the `safe_join_path` function and replace `path_in_workspace` with 

```
def path_in_workspace(relative_path: str | Path) -> Path:
    """Get full path for item in workspace

    Parameters:
        relative_path (str | Path): Path to translate into the workspace

    Returns:
        Path: Absolute path for the given path in the workspace
    """
    return WORKSPACE_PATH.joinpath(relative_path)

2023-04-19 13:59 UTC, primaryobjects commented
> The correct resolution, I think, is to delete the `safe_join_path` function and replace `path_in_workspace` with

@collijk The PR has been revised per your suggestion. Tested locally, this appears to work correctly. Would you mind testing? Thank you.

2023-04-20 01:39 UTC, Pwuts commented
Because of issues in a number of libraries and other dependencies we have dropped support for Python <3.10. Also, this PR outright eliminates workspace restriction which is an important security measure.

2023-04-20 01:39 UTC, closed without merging