Fix speak on mac
Significant-Gravitas/Auto-GPT pull request #2550
Opened 2023-04-19 15:39 UTC by patrickmwatson

### Background

### Changes

### Documentation

### Test Plan

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-04-19 21:45 UTC, k-boikov commented
I don't think this should be under # Testing dependencies

2023-04-20 14:12 UTC, k-boikov requested changes

2023-04-20 14:12 UTC, k-boikov commented on requirements.txt
> +pyobjc
Please explain why is the requirement under Testing dependencies. Also can you give example of what is fixed with it?

2023-04-28 09:10 UTC, Pwuts commented
Missing explanation

2023-04-28 09:10 UTC, closed without merging