add --ignore option to data_ingestion.py to ignore directories like .git
Significant-Gravitas/Auto-GPT pull request #2577
Opened 2023-04-19 19:25 UTC by jondwillis

### Background

I used data_ingestion.py to pre-seed my database, but it got bogged down ingesting dependencies and git files.
### Changes

Add --ignore to data_ingestion.py and update documentation
### Documentation

documented in the local README.md and in code comments
### Test Plan

N/A (see below)
### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes 

There are no existing tests that I found for data_ingestion.py

2023-04-19 19:56 UTC, ravefaces approved these changes

2023-04-20 02:41 UTC, jondwillis commented
Rebased, force pushed. 

I also fixed an issue where the ignore list wasn't being sent with the search_files command.

2023-04-20 04:44 UTC, hdkiller approved these changes

2023-04-27 19:43 UTC, Pwuts requested changes

2023-04-27 19:43 UTC, Pwuts commented on autogpt/commands/file_operations.py
> +@command("search_files", "Search Files", '"directory": "<directory>", "ignore_list": "<list_of_directories_to_ignore>')
```suggestion
@command("search_files", "Search Files", '"directory": "<directory>", "ignore_list": "<list of directories to ignore>"')
```

2023-04-27 19:43 UTC, Pwuts commented on README.md
> +  --ignore                 For use in combination with --dir, a list of directories to ignore
Please include list format in instructions

2023-04-27 19:43 UTC, Pwuts commented on data_ingestion.py
> +    )
`--ignore foo --ignore bar`
or
`--ignore foo bar`
?

2023-04-27 19:43 UTC, Pwuts commented on autogpt/commands/file_operations.py
> +        dirs[:] = [d for d in dirs if d not in ignore_list]
```suggestion
        dirs = [d for d in dirs if d not in ignore_list]
```

2023-05-05 00:55 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-05-30 20:44 UTC, jondwillis commented
@Pwuts you can go ahead and close this

2023-05-30 21:26 UTC, closed without merging