Update image_gen.py file
Significant-Gravitas/Auto-GPT pull request #2691
Opened 2023-04-20 15:31 UTC by AndresCdo

### Background
Size parameter was not used in required function parameter.

### Changes
Adds size variable to functions parameters.

2023-04-20 16:09 UTC, hdkiller requested changes

2023-04-20 16:09 UTC, hdkiller commented on autogpt/commands/image_gen.py
>      Args:
Seems like you forgot to update the Args: within the comments regarding the new argument.

2023-04-20 18:44 UTC, hdkiller approved these changes

2023-04-20 19:48 UTC, goern commented
/lgtm ;)

2023-04-20 21:17 UTC, AndresCdo commented
@Torantulino @goern @hdkiller this PR is ready to merge.

2023-04-20 22:37 UTC, k-boikov approved these changes

2023-04-21 02:00 UTC, Pwuts approved these changes

2023-04-21 02:00 UTC, merged