Add function and class descriptions in tests for improved code readability
Significant-Gravitas/Auto-GPT pull request #2715
Opened 2023-04-20 19:06 UTC by AndresCdo

### Background
The codebase of the project has grown in complexity and size, making it difficult for developers to understand the purpose and functionality of the various functions and classes. To address this issue, a pull request has been submitted to add descriptions to all functions and classes in the codebase.

### Changes
- The pull request adds descriptions to all functions in the codebase. These descriptions provide a brief overview of the purpose of each function, its input parameters, and its return values. This makes it easier for other developers to understand the functionality of each function and how to use it correctly.
- The pull request also adds descriptions to all classes in the codebase. These descriptions provide a brief overview of the purpose of each class, its properties and methods, and how it relates to other classes in the codebase. This makes it easier for other developers to understand the structure and hierarchy of the codebase and how different components work together.
- The pull request includes updates to the project's documentation to reflect the new function and class descriptions. This helps other developers understand how to work with the codebase and how to use the various functions and classes correctly.
- The pull request also reviews existing function and class descriptions to ensure that they are accurate, up-to-date, and consistent with the new descriptions. This helps maintain the integrity and accuracy of the codebase's documentation over time.

2023-04-20 21:17 UTC, AndresCdo commented
@Torantulino this PR is ready to merge.

2023-04-20 23:16 UTC, hdkiller approved these changes

2023-04-20 23:17 UTC, hdkiller commented
@BillSchumacher LGTM

2023-04-21 02:09 UTC, Pwuts requested changes
Descriptions and inline documentation is nice, but only when it is useful. A *lot* of these comments are so obvious they might as well be removed.

2023-04-21 02:09 UTC, Pwuts commented on tests/browse_tests.py
> +        """Test the extract_hyperlinks function"""
...
```
i += 1; # adds 1 to i
```

2023-04-21 11:14 UTC, AndresCdo commented on tests/browse_tests.py
> +        """Test the extract_hyperlinks function"""
Solved.

2023-04-21 13:24 UTC, Pwuts requested changes
Still way too verbose. An extra line of text that doesn't add value is just clutter. If the name of a function and the names of the parameters already make obvious what it does, it doesn't need a docstring that is basically a copy of the function name.

Target: try to achieve the informative goals while adding as few lines as possible.

2023-04-21 14:22 UTC, AndresCdo commented
> Still way too verbose. An extra line of text that doesn't add value is just clutter. If the name of a function and the names of the parameters already make obvious what it does, it doesn't need a docstring that is basically a copy of the function name.
> 
> Target: try to achieve the informative goals while adding as few lines as possible.

Thank you for your feedback on my recent changes to the project. I understand your concerns about the docstrings being too verbose and cluttered, and I appreciate your suggestion to achieve the informative goals while adding as few lines as possible.

However, I strongly believe that these changes are necessary for the project's maintainability and ease of use. While some of the docstrings may have been redundant, I aimed to provide as much context and information as possible to help other developers understand the purpose and functionality of each function.

That being said, I will review the docstrings and refactor them where possible to achieve a better balance between clarity and conciseness. I would also like to emphasize that this pull request is important and should be merged as soon as possible to ensure that the project remains organized and well-documented.

Once again, thank you for your feedback, and please let me know if you have any further concerns or suggestions.

2023-04-22 02:00 UTC, Pwuts requested changes
In my previous review I asked to remove redundant comments. Following that review, you pushed some commits with a net total of 15 lines *added*. Some of the descriptions were improved, but you stripped only 3 of the 30+ remaining redundant comments.

This is the last feedback you'll get from me. Next time I'll either merge or bounce it depending on whether you have actually applied the requested changes. See comments below; ✂️ means remove.

Some test classes have a docstring like `Test cases for ... in [path_to_file]`. Please remove the file path from the docstring in these cases, as it is subject to change and won't be caught by automatic refactoring.

2023-04-22 02:00 UTC, Pwuts commented on tests/integration/memory_tests.py
> +        """
```suggestion
    def generate_random_string(self, length):
```
(ofc also rename where it's used)

2023-04-22 02:00 UTC, Pwuts commented on tests/integration/memory_tests.py
> +        # Add the example texts to the cache
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/integration/memory_tests.py
> -        # Add some random strings to test noise
This line was actually useful, please add it back

2023-04-22 02:00 UTC, Pwuts commented on tests/integration/weaviate_memory_tests.py
> +
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/integration/memory_tests.py
> +
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/integration/milvus_memory_tests.py
> +            """
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/integration/milvus_memory_tests.py
>          def random_string(self, length: int) -> str:
```suggestion
        def generate_random_string(self, length: int) -> str:
```
(and references)

2023-04-22 02:00 UTC, Pwuts commented on tests/local_cache_test.py
> +    """Unit tests for the LocalCache class in memory/local.py."""
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/mocks/mock_commands.py
> +        arg2 (str): The second argument.
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # This function is static because it is not used by any other test cases.
```suggestion
    def example_method(arg1: int, arg2: str) -> str:
```

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # Create a Command object with the example_function.
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # Create a Command object with the example_function.
```suggestion
        """Test that Command(*args) calls and returns the result of method(*args)."""
```

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # Call the Command object like a function.
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # Create a Command object with the example_function.
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # Call the Command object with invalid arguments.
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # Check that the default signature is correct.
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # Create a Command object with the example_function.
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        """Test that a custom signature can be set."""
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # Check that the custom signature is correct.
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
> +        # Return a string with the two arguments separated by a dash
```suggestion
    def example_command_method(arg1: int, arg2: str) -> str:
```

2023-04-22 02:00 UTC, Pwuts commented on tests/test_commands.py
>          return f"{arg1} - {arg2}"
These two lines are a perfect example of what not to do.

2023-04-22 02:00 UTC, Pwuts commented on tests/test_image_gen.py
> +    """Get the last item in a list."""
```suggestion
    """Extract the file path from the output of `generate_image()`"""
```

2023-04-22 02:00 UTC, Pwuts commented on tests/test_image_gen.py
> +        """Set up the test class."""
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_image_gen.py
> +
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_json_parser.py
> +        """Test that a valid JSON string can be parsed."""
The previous description was better, please revert

2023-04-22 02:00 UTC, Pwuts commented on tests/test_token_counter.py
> +        """Test that the name is counted as a token."""
incorrect

2023-04-22 02:00 UTC, Pwuts commented on tests/test_token_counter.py
> +
✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/test_token_counter.py
> +        """Test that the message tokens are counted correctly."""
You have added this exact same docstring in 8 places in this file. Better to just add a summary of the tests to the class docstring and remove these 8.

2023-04-22 02:00 UTC, Pwuts commented on tests/test_token_counter.py
> +        # GPT-4 should count 15 tokens
The LLM doesn't count the tokens, same on line 52 and 60 and 75. Also redundant as the `assertEquals` is self-explanatory. ✂️

2023-04-22 02:00 UTC, Pwuts commented on tests/unit/json_tests.py
> +        """Test that a valid JSON string can be parsed"""
```suggestion
        """Test that a valid JSON string is parsed"""
```

2023-04-22 02:00 UTC, Pwuts commented on tests/unit/models/test_base_open_api_plugin.py
None of these comments really adds any value since the names are descriptive enough. Please remove all of them.

2023-04-22 02:00 UTC, Pwuts commented on tests/unit/test_browse_scrape_text.py
> +        """Test that the function returns an error message when an invalid or unreachable url is provided."""
```suggestion
        """Test that scrape_text returns an error message when an invalid or unreachable url is provided."""
```

2023-04-22 02:00 UTC, Pwuts commented on tests/unit/test_browse_scrape_links.py
This file already contains doc comments. Please deduplicate or revert.

2023-04-22 02:00 UTC, Pwuts commented on tests/unit/test_browse_scrape_text.py
This file already contains doc comments. Please dedup or revert.

2023-04-22 02:00 UTC, Pwuts commented on tests/unit/test_plugins.py
> +    """Test that the denylist_allowlist_check function works"""
Please remove all of these

2023-04-22 02:00 UTC, Pwuts commented on tests/unit/test_plugins.py
> +    """Test that the inspect_zip_for_module function works"""
✂️ doesn't add any value over the function name

2023-04-22 02:00 UTC, Pwuts commented on tests/unit/test_plugins.py
> +    """Mock config object for testing the denylist_allowlist_check function"""
✂️

2023-04-22 13:10 UTC, AndresCdo commented
@Pwuts changes suggested were done.

2023-04-22 15:48 UTC, Pwuts commented
Thanks

2023-04-22 19:03 UTC, AndresCdo commented on tests/integration/memory_tests.py
> -        # Add some random strings to test noise
This has already been fixed. But still appears as pending.

2023-04-22 19:03 UTC, AndresCdo commented on tests/unit/test_browse_scrape_text.py
This has already been fixed. But still appears as pending.

2023-04-24 12:55 UTC, merged