Dockerfile: reduce layer bloat
Significant-Gravitas/Auto-GPT pull request #2821
Opened 2023-04-21 15:14 UTC by DrMurx

### Background

The current Dockerfile generates a large amount of unneeded layers containing copies of the APT cache at build time.  

### Changes

A GPT model advised to modify the Dockerfile like this. ;-)

### Documentation

This is what the GPT model had to say about its changes:

In this new version, we've merged all installation steps in a single `RUN` command. This way, we can reduce the number of layers in the image and avoid bloating it unnecessarily. We first install all the dependencies except Chromium and Firefox-ESR. After that, we add the Google repository key and repository to the sources list, and then we update the package lists again and install Chromium and Firefox-ESR. We've added a clean step to remove the apt cache and other unused files, reducing the size of the resulting layer.

### Test Plan

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] n/a I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [ ] n/a I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

2023-04-21 16:00 UTC, hdkiller approved these changes

2023-04-21 16:05 UTC, Wladastic commented on Dockerfile
> +    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
I know adding && makes it more safe but it's super hard to read now

2023-04-21 16:47 UTC, DrMurx commented on Dockerfile
> +    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
That's more a matter of habits. If I write a Dockerfile occasionally, I might not be used to that syntax. If I do it every day, I don't even notice the `&&` and the `\` anymore.

Btw, it has nothing to do with "more safety", as there's no "less safe" alternative to it. It's a hard requirement that all commands in each `RUN` line get executed, and if only one of them fails, the docker build should fail too.

Creating docker images without apt cache clutter is simply best practice. Here's what a GPT model has to say about this:

> When creating a Dockerfile, it's generally a good practice to execute `apt-get update` to ensure that the package list is up to date before installing any packages. However, it's also a good practice to clean up the cache in the same layer to keep the image size small.

2023-04-21 18:12 UTC, richbeales commented
Anecdotally our Docker Build CI task took twice as long on this PR.  Would want to check that before committing.

2023-04-21 18:23 UTC, DrMurx commented
> Anecdotally our Docker Build CI task took twice as long on this PR. Would want to check that before committing.

@richbeales That may very well be and it heavily depends on how you've organized your builds. 

Fewer container image layers also means fewer opportunities for the [build cache](https://docs.docker.com/build/cache/). I would argue that layer caching is most beneficial during development where you execute `docker build` frequently in your local environment, but a CI build job should always start clean (ie `docker build --no-cache`) to avoid stale dependencies.

2023-04-22 07:47 UTC, ntindle approved these changes

2023-05-05 00:56 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-05-07 10:43 UTC, Boostrix commented
would also be interested in less bloat :+1:

2023-05-22 10:36 UTC, Pwuts requested changes
Cleaning up the apt cache is good, but please maintain the layer separation we have now for caching sake.

2023-06-07 00:38 UTC, Pwuts approved these changes

2023-06-07 01:13 UTC, Pwuts commented
This is saving ~18MB overall.. just over 1% of the release image :')

2023-06-07 01:14 UTC, merged