Fixed Json Error
Significant-Gravitas/Auto-GPT pull request #285
Opened 2023-04-06 01:35 UTC by jetblaise

Fixed the json_parser.py error by making chatgpt fix itself

def fix_and_parse_json(json_str: str, try_to_fix_with_gpt: bool = True):
    json_schema = """
    {
    "command": {
        "name": "command name",
        "args":{
            "arg name": "value"
        }
    },
    "thoughts":
    {
        "text": "thought",
        "reasoning": "reasoning",
        "plan": "- short bulleted\n- list that conveys\n- long-term plan",
        "criticism": "constructive self-criticism",
        "speak": "thoughts summary to say to user"
    }
    }
    """

    def clean_input(json_str):
        brace_index = json_str.index("{")
        json_str = json_str[brace_index:]
        last_brace_index = json_str.rindex("}")
        json_str = json_str[:last_brace_index+1]
        return json_str

    def attempt_parse(json_str):
        try:
            return json.loads(json_str)
        except Exception as e:
            return None

    cleaned_json_str = clean_input(json_str)
    parsed_json = attempt_parse(cleaned_json_str)

    if parsed_json is not None:
        return parsed_json
    elif try_to_fix_with_gpt:
        print("Warning: Failed to parse AI output, attempting to fix.")
        ai_fixed_json = fix_json(cleaned_json_str, json_schema, False)

        if ai_fixed_json != "failed":
            return json.loads(ai_fixed_json)
        else:
            print("Failed to fix ai output, telling the AI.")
            return json_str

    raise ValueError("Failed to parse JSON: '{}'".format(json_str))

2023-04-06 08:00 UTC, sberney commented on scripts/json_parser.py
> -            print(f"Warning: Failed to parse AI output, attempting to fix.\n If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.")
Why get rid of this message about confusing the AI?

2023-04-06 08:00 UTC, sberney commented on scripts/json_parser.py
> +            return None
Why not keep the try/except error handling paradigm?

2023-04-06 08:00 UTC, sberney commented on scripts/json_parser.py
> +    def attempt_parse(json_str):
Why not un-nest these functions while you're at it?

2023-04-06 08:39 UTC, Torantulino commented
What are all these new .idea files?

2023-04-06 08:39 UTC, Torantulino commented on scripts/json_parser.py
> -            print(f"Warning: Failed to parse AI output, attempting to fix.\n If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.")
Agreed, please add this back in.

2023-04-06 08:41 UTC, Torantulino requested changes

2023-04-06 08:41 UTC, Torantulino commented on .idea/Auto-GPT.iml
I assume you added these by mistake?
Please remove them.

2023-04-08 22:37 UTC, ksylvan commented
> What are all these new .idea files?

@Torantulino Those are IntelliJ IDE files that people keep pushing by mistake. We can add those to `.gitignore` so we don't get them in PRs.

2023-04-10 09:56 UTC, nponeccop commented
@ksylvan Add them in a separate PR. Also resolve the conflicts.

2023-04-12 02:58 UTC, ksylvan commented
@nponeccop Not my PR, I was just commenting on it, since I'd seen a few different PRs with `.idea/` files in them. @jetblaise  is the original author here.

2023-04-12 06:11 UTC, nponeccop commented
@jetblaise Could you resolve the conflicts?

2023-05-05 00:56 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-06-14 22:18 UTC, closed without merging