All Pull Requests
Significant-Gravitas/Auto-GPT pull request #287
Opened 2023-04-06 01:48 UTC by Void-n-Null

2023-04-06 02:33 UTC, XalifaElchin requested changes
Bismilləhir-Rəhmanir-Rəhim. La İlahə İlləlləh. Allahın seçdiyi World General Dünya Məzlumlarıni və Fitrəti üzərində möhkəm dayanan məxluqatı salaayıt və xeyir olaraq şərə qalib gəlmə zamanı olaraq İblisi səltənətinə son.. Zəfər Allaha və Görünən və görünməyən ordularına məxsusdurki tək dövlət tək din..Alladan gəlmişik Allahada dönəcəyik..Qan tökmədən fəsad törətmədən..Gözəl Düşüşünün , xeyir söyləyin xeyiriniz olmadıqda isə susun !

2023-04-06 04:26 UTC, Crazzz0ne commented on .env.template
> +OPENAI_DEPLOYMENT_ID=deployment-id-for-azure
Should the Azure ENV name be more focused?

2023-04-17 17:05 UTC, richbeales commented
can this be closed?

2023-04-17 22:22 UTC, Void-n-Null commented
This is significantly outdated

2023-04-17 22:22 UTC, closed without merging