Adding support for openai_organization env variable
Significant-Gravitas/Auto-GPT pull request #289
Opened 2023-04-06 03:22 UTC by kaneda2004

Addresses #270

2023-04-06 08:50 UTC, Torantulino requested changes

2023-04-06 08:50 UTC, Torantulino commented on env.template
This file is named incorrectly. 
It should be `.env.template`

2023-04-06 16:14 UTC, kaneda2004 commented on env.template
Thank you - my apologies - amended.

2023-04-10 10:00 UTC, nponeccop commented
@kaneda2004 Resolve the conflicts

2023-04-10 14:01 UTC, nponeccop approved these changes

2023-04-11 13:39 UTC, nponeccop commented
@kaneda2004 Resolve the conflicts, it got outdated again due to other merges.

2023-05-05 05:56 UTC, anonhostpi commented
I think this needs to be done after the re-arch. Switching APIs is a proposed feature, and I believe that adding/hotswitching APIs is a method done best after the team finishes implementing APIs as plugins rather than internal parts of AutoGPT.

The reason for this is that there are so many APIs to switch out, that there seems to be a need to loosen how tightly coupled AutoGPT is to each _individual_ API

2023-05-05 09:05 UTC, Boostrix commented
As long as it's strictly config only, or introducing new options, should be pretty safe to consider even prior to the /during the re-arch

2023-05-28 05:09 UTC, p-i- commented
This looks sensible.

2023-05-30 21:12 UTC, richbeales submitted a review, later dismissed

2023-05-31 01:51 UTC, merwanehamadi approved these changes

2023-05-31 02:02 UTC, merged