Update docker-compose so it can run properly now
Significant-Gravitas/Auto-GPT pull request #2966
Opened 2023-04-23 00:56 UTC by namnx228

### Background

Update the docker-compose it can run properly with Redis support.

### Changes

- Update the docker-compose file to reflect the new mounting point
- Update doc file to describe how to run docker-compose with redis.

### Documentation

The change is small and can be understood by this pull request description. 

### Test Plan

Follow the step I described in the doc file change.

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

2023-04-23 01:07 UTC, namnx228 commented
@Torantulino @BillSchumacher  Please take a look

2023-04-23 05:54 UTC, ppetermann commented
partially duplicates #2923

2023-04-23 05:55 UTC, ppetermann commented on docker-compose.yml
> +    container_name: redis-stack-server
don't name containers if not necessary, naming containers can create conflicts with other containers of the same name

2023-04-23 05:57 UTC, ppetermann requested changes

2023-04-23 05:57 UTC, ppetermann commented on docs/configuration/memory.md
> +REDIS_HOST=redis-stack-server
that would explain why you are naming the container. use the service name instead (redis), and docker will take care of the rest

2023-04-26 20:52 UTC, Pwuts commented
Closing as deprecated; this was already fixed in #1843

2023-04-26 20:52 UTC, closed without merging