Added type hints to function and method signature
Significant-Gravitas/Auto-GPT pull request #3061
Opened 2023-04-23 22:04 UTC by ofirkris

Added type hints to function and method signatures, which helps with readability, maintainability, and reduces the chances of introducing bugs. Changed the get_ada_embedding function to return Dict instead of None, since it appears to return a dictionary object.

### Background

### Changes

### Documentation

### Test Plan

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-04-28 00:49 UTC, ntindle requested changes
Sep. Into two prs for changes to function and documentation of function

2023-04-28 00:49 UTC, ntindle commented on autogpt/memory/base.py
> +
wehre does this change come from?

2023-05-05 00:54 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-06-15 23:06 UTC, Pwuts commented
This PR was deprecated by #4208. Still, thanks for submitting!

2023-06-15 23:06 UTC, closed without merging