Simplify terms like "allowlisted". Implement plugin denial env.
Significant-Gravitas/Auto-GPT pull request #3254
Opened 2023-04-25 21:39 UTC by bobisme

### Background
I noticed an inclusive-language change where terms like "white" and "black" were replaced with "allow" and "deny" which resulted in awkward non-words like "allowlisted."  Simpler terms would make the code cleaner and clearer.

### Changes

* Changed "allowlist" and "denylist" to thinks like "allowed" and "denied" for more natural language.
* Note: This affects the ALLOWLISTED_PLUGINS env variable.
* Also noticed the config for denied plugins was unimplemented, so I added that.

### Documentation

Functions were already documented.

### Test Plan
Unit tests already covered this functionality.

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

2023-05-01 14:10 UTC, lc0rp commented on autogpt/config/config.py
> +        self.plugins_denied = os.getenv("DENIED_PLUGINS")
Nice. I was about to implement this.

A slight suggestion to ensure self.plugins_denied is always a list, even when unset, matching the ALLOWED_PLUGINS behavior.

```
self.plugins_denied = os.getenv("DENIED_PLUGINS", [])
```

2023-05-05 00:55 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-06-11 22:43 UTC, Pwuts requested changes
I'm thinking we need backwards compatibility for the old keys in `.env`

2023-06-11 22:43 UTC, Pwuts commented on .env.template
> +DENIED_PLUGINS=
This makes sense 👍🏼

2023-06-11 22:43 UTC, Pwuts commented on autogpt/config/config.py
> +        plugins_allowed = os.getenv("ALLOWED_PLUGINS")
`plugins_allowed` is a bit of an ambiguous name: is it a `bool` indicating whether plugins are allowed, or a `list` of allowed plugins?

2023-06-11 22:43 UTC, Pwuts commented on autogpt/plugins.py
> +def check_allowed(plugin_name: str, cfg: Config) -> bool:
```suggestion
def is_allowed(plugin_name: str, cfg: Config) -> bool:
```

2023-07-07 13:46 UTC, Torantulino commented
@CodiumAI-Agent

2023-07-07 13:46 UTC, CodiumAI-Agent commented
Preparing review...

2023-07-07 13:46 UTC, CodiumAI-Agent commented
## PR Analysis

- 🎯 **Main theme:** Renaming of variables and functions for better clarity and inclusivity
- 🔍 **Description and title:** Yes
- 📌 **Type of PR:** Refactoring
- 🧪 **Relevant tests added:** Yes
- ✨ **Minimal and focused:** Yes, the PR is focused on renaming variables and functions related to plugin loading for better clarity and inclusivity.
- 🔒 **Security concerns:** No, the PR does not introduce any security concerns as it mainly involves renaming of variables and functions.
## PR Feedback

- 💡 **General PR suggestions:** The PR is well-structured and follows good practices. The renaming of variables and functions improves the clarity and inclusivity of the code. However, it's important to note that this PR introduces a breaking change by renaming environment variables. This should be clearly communicated to users and documented.

- 🤖 **Code suggestions:**


  - **relevant file:** autogpt/config/config.py
   **suggestion content:** Consider adding a fallback mechanism to support the old environment variables (ALLOWLISTED_PLUGINS and DENYLISTED_PLUGINS) for backward compatibility. This can be done by checking if the new environment variables are not set, then fallback to the old ones. [important]


  - **relevant file:** autogpt/plugins.py
   **suggestion content:** The function name 'check_allowed' could be more descriptive. Consider renaming it to 'is_plugin_allowed' to make it clear that it returns a boolean indicating whether a plugin is allowed or not. [medium]


  - **relevant file:** tests/unit/test_plugins.py
   **suggestion content:** Update the test function names to reflect the new function name 'check_allowed'. For example, 'test_denylist_allowlist_check_denylist' could be renamed to 'test_check_allowed_when_denied'. [medium]


  - **relevant file:** .env.template
   **suggestion content:** Add comments in the .env.template file to inform users about the change in environment variables and the potential need to update their environment configurations. [important]


### How to use
> Tag me in a comment '@CodiumAI-Agent' to ask for a new review after you update the PR.
> You can also tag me and ask any question, for example '@CodiumAI-Agent is the PR ready for merge?'

2023-09-08 13:40 UTC, closed without merging