remove print_total_cost variable and optimization of docstring format
Significant-Gravitas/Auto-GPT pull request #3291
Opened 2023-04-26 04:58 UTC by lengweiping1983

### Background

### Changes

### Documentation

### Test Plan

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-04-26 08:21 UTC, hdkiller commented
I think this should be 3 different PRs.

2023-04-26 08:22 UTC, hdkiller approved these changes
Otherwise it's LGTM.

2023-04-26 09:07 UTC, ntindle requested changes
Fill out pr template with details on why

2023-04-26 13:02 UTC, Pwuts submitted a review, later dismissed

2023-04-27 18:39 UTC, Pwuts requested changes

2023-04-27 18:39 UTC, Pwuts commented on autogpt/api_manager.py
> +        deployment_id: str | None = None,
this is the only change I would like to merge

2023-04-28 12:56 UTC, closed without merging