Continue prompt fix
Significant-Gravitas/Auto-GPT pull request #335
Opened 2023-04-06 17:06 UTC by sw4rm3r

2023-04-08 19:58 UTC, nponeccop requested changes
Remove the irrelevant changes and submit them in a separate PR

2023-04-08 19:58 UTC, nponeccop commented on .env.template
This change shouldn't be in this PR

2023-04-08 19:58 UTC, nponeccop commented on .gitignore
This one isnt related to the prompt fix either

2023-04-10 10:17 UTC, nponeccop commented
@sw4rm3r Resolve the conflicts

2023-05-05 00:56 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-06-14 22:16 UTC, Pwuts commented
* No description
* Invalid changes (deleting `.env.template`)
* No response to review
* Conflicts with base branch

Thanks for submitting, unfortunately we can't process this. Feel free to contribute again, but be sure to fill out the PR description (template).

2023-06-14 22:16 UTC, closed without merging