Plugin for text embedding
Significant-Gravitas/Auto-GPT pull request #3462
Opened 2023-04-28 09:56 UTC by ddannyc

### Background
This pull request duplicates [#2804](https://github.com/Significant-Gravitas/Auto-GPT/pull/2804), but that pull request did not pass the tests and may not be merged.

### Changes
* autogpt/llm_utils.py#create_embedding  check and handle embedding
* autogpt/models/base_open_ai_plugin.py add embedding plugin

### Documentation

### Test Plan

tests/unit/test_plugins.py::test_scan_plugins_openai

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

2023-05-01 23:49 UTC, ntindle requested changes

2023-05-01 23:49 UTC, ntindle commented on autogpt/models/base_open_ai_plugin.py
> +        """This method is called when the chat completion is done.
Doc string is incorrect here

2023-05-01 23:49 UTC, ntindle commented on autogpt/llm/llm_utils.py
> +                return embedding
Can multiple embeddings work here? "No, that's annoying is an acceptable answer"

2023-05-02 07:04 UTC, ddannyc commented on autogpt/llm/llm_utils.py
> +                return embedding
The embedding plugin works like chat completion; for now, it only accepts a one plugin.

2023-05-05 00:54 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-07-14 20:41 UTC, Pwuts commented
Closing this as a duplicate of #2804. Still, thanks for picking it up! Turns out, it was just the linter complaining on that PR, so would have been easy to fix. Now it took a little bit more work to get it up to date with `master`, but still fairly easy to fix up & merge. :)

2023-07-14 20:41 UTC, closed without merging