centralize prompt: setup.py
Significant-Gravitas/Auto-GPT pull request #3955
Opened 2023-05-07 14:08 UTC by Eggrolling-hu

### Background

### Changes

### Documentation

### Test Plan

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-05-07 14:24 UTC, merwanehamadi requested changes

2023-05-07 14:24 UTC, merwanehamadi commented on autogpt/prompts/default_prompts.py
> +USER_DESIRE_DEFAULT_PROMOTE = (
DEFAULT_USER_DESIRE

2023-05-07 14:24 UTC, merwanehamadi commented on autogpt/prompts/default_prompts.py
> +TASK_PROMPT_AICONFIG_AUTOMATIC = (
DEFAULT_TASK_PROMPT_AICONFIG_AUTOMATIC

2023-05-07 14:24 UTC, merwanehamadi commented on autogpt/prompts/default_prompts.py
> +SYSTEM_PROMPT_AICONFIG_AUTOMATIC = ("""
DEFAULT_SYSTEM_PROMPT_AICONFIG_AUTOMATIC

2023-05-07 14:24 UTC, merwanehamadi commented on autogpt/prompts/default_prompts.py
> +)  # Default prompt
Create categories so people know where the constant is coming from.

Here it's 
#########################Setup.py#################################

2023-05-07 14:24 UTC, merwanehamadi commented on autogpt/prompts/default_prompts.py
> +SYSTEM_PROMPT_AICONFIG_AUTOMATIC = ("""
RUN : 
black .
isort .

2023-05-07 14:43 UTC, merwanehamadi requested changes

2023-05-07 14:43 UTC, merwanehamadi commented on autogpt/prompts/default_prompts.py
> +DEFAULT_USER_DESIRE_PROMOTE = "Write a wikipedia style article about the project: https://github.com/significant-gravitas/Auto-GPT"  # Default prompt
DEFAULT_USER_DESIRE_PROMOTE
=> DEFAULT_USER_DESIRE_PROMPT

2023-05-07 14:47 UTC, merwanehamadi requested changes

2023-05-07 14:47 UTC, merwanehamadi commented on autogpt/prompts/default_prompts.py
> +DEFAULT_SYSTEM_PROMPT_AICONFIG_AUTOMATIC = """
run isort .

2023-05-08 01:30 UTC, merwanehamadi approved these changes

2023-05-08 01:51 UTC, closed without merging

2023-05-08 03:04 UTC, anonhostpi commented
#3858

2023-05-08 03:04 UTC, anonhostpi commented
#3990