Revise message broker interface
Significant-Gravitas/Auto-GPT pull request #3986
Opened 2023-05-08 01:30 UTC by collijk

Updates the abstract interface for the message broker as it starts to meet the real world in #3969

2023-05-08 01:31 UTC, collijk commented on autogpt/core/command/base.py
> -from typing import Any, Callable, Optional, Tuple, Dict
Everything in this file is from running black.  Sorry!

2023-05-08 04:42 UTC, anonhostpi commented
I'm assuming this is related to #3831

2023-05-08 14:34 UTC, rihp requested changes

2023-05-08 14:34 UTC, rihp commented on autogpt/core/messaging/base.py
> +    sender: Sender
i like this approach to cohesively have the sender in the meta data

2023-05-08 14:34 UTC, rihp commented on autogpt/core/messaging/base.py
> +    # TODO: what else goes here?
maybe commands and arguments ?

2023-05-08 14:34 UTC, rihp commented on autogpt/core/messaging/base.py
> +    content: dict  # Some json struct we can define with a strict schema
Would this be the msg broker contract we have talked about in the past?

2023-05-08 14:34 UTC, rihp commented on autogpt/core/messaging/base.py
> +    content: dict  # Some json struct we can define with a strict schema
Where in the code should this structure be defined ?

2023-05-08 14:34 UTC, rihp commented on autogpt/core/messaging/base.py
> +    def send_message(self, content: dict, **extra_metadata) -> None:
should there be a return type to confirm that the message was sent? Maybe a boolean?

2023-05-08 14:34 UTC, rihp commented on autogpt/core/messaging/base.py
> +    def __repr__(self) -> str:
This method could return the metadata from the channel and the most recent message for example

2023-05-08 14:34 UTC, rihp commented on autogpt/core/messaging/base.py
> +    def send_message(self, message: Message) -> None:
should this return a boolean?

2023-05-09 00:12 UTC, collijk commented on autogpt/core/messaging/base.py
> +    # TODO: what else goes here?
Messages won't always have commands, I think.  The `additional_metadata` dict gives us a lot of flexibility for now until you and @merwanehamadi and others can pull together the data interchange standard

2023-05-09 00:14 UTC, collijk commented on autogpt/core/messaging/base.py
> +    content: dict  # Some json struct we can define with a strict schema
The content and the metadata. 

They should get define in this subpackage, but I'm not sure what tool you want to use.  There are lots of good ones, though pydantic might be industry standard at this point.  I'm agnostic as long as the schema is enforcable.

2023-05-09 00:15 UTC, collijk commented on autogpt/core/messaging/base.py
> +    def send_message(self, content: dict, **extra_metadata) -> None:
Good Q.  I'm not sure if the send receipt would be implementation specific.  We can readjust when we do our first real message broker implementation

2023-05-09 03:13 UTC, collijk commented on autogpt/core/messaging/base.py
> +    def __repr__(self) -> str:
`repr`s have to be strings. Concrete classes can determine what that string should be.

2023-05-09 03:13 UTC, collijk commented on autogpt/core/messaging/base.py
> +    def send_message(self, content: dict, **extra_metadata) -> None:
I'll swap to a bool for now.

2023-05-09 03:14 UTC, merged