Enabling/disabling none/all of plugins from .env file, small change to plugins.py
Significant-Gravitas/Auto-GPT pull request #4036
Opened 2023-05-08 23:25 UTC by TrajanWJ

### Background

### Changes

### Documentation

### Test Plan

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-05-08 23:29 UTC, TrajanWJ commented
Ive had this done with my copy for a while, just an ease of use thing for plugins. Not a big deal

2023-05-10 05:36 UTC, ntindle requested changes
Add to docs/

2023-05-10 13:25 UTC, TrajanWJ commented
> Add to docs

Will do ASAP, wanted to do some work on docs anyways. I think we should consider adding a "for devs" sections that explains the internals and architecture, or at least the principals that AUTOGPT uses to function.

2023-05-18 06:39 UTC, ntindle approved these changes

2023-05-19 17:27 UTC, k-boikov approved these changes

2023-05-19 17:33 UTC, merged