Incremented Version  BULLETIN.md
Significant-Gravitas/Auto-GPT pull request #4236
Opened 2023-05-16 03:13 UTC by AlexKissiJr

Incremented version number

2023-05-16 03:26 UTC, gravelBridge commented
Hi, could you also modify the other information too? Such as "Over a week and 275 pull requests have passed since v0.2.2" etc...

2023-05-16 05:06 UTC, AlexKissiJr commented
> Hi, could you also modify the other information too? Such as "Over a week and 275 pull requests have passed since v0.2.2" etc...

I haev also updated the Pull request number. Thank you

2023-05-16 07:05 UTC, Boostrix commented
> Hi, could you also modify the other information too? Such as "Over a week and 275 pull requests have passed since v0.2.2" etc...

We should probably script that to automate these portions ?

2023-05-16 07:06 UTC, Boostrix commented on BULLETIN.md
> +Over a week and 47 pull requests have passed since v0.2.2, and we are happy to announce
v0.2.2 also needs to be adapted to read 0.3.0, right ?

2023-05-16 12:41 UTC, k-boikov commented on BULLETIN.md
> +Over a week and 47 pull requests have passed since v0.2.2, and we are happy to announce
since v0.2.2 is not right, it whould be 0.3.0

2023-05-16 16:28 UTC, gravelBridge commented
Hello, please update 0.2.2 to 0.3.0.

2023-05-16 17:04 UTC, gravelBridge commented
Although this is good, for this to be a substantial pr, please update the entire bulletin with up to date information and updated. You can get information from the release notes. Thank you!

2023-05-16 17:42 UTC, AlexKissiJr commented
> Although this is good, for this to be a substantial pr, please update the entire bulletin with up to date information and updated. You can get information from the release notes. Thank you!

@gravelBridge I updated it per your request. let me know if that works. Thank you

2023-05-16 17:46 UTC, Boostrix approved these changes

2023-05-16 23:29 UTC, gravelBridge commented
Looks good to me!

2023-05-16 23:30 UTC, gravelBridge approved these changes
LGTM

2023-05-16 23:48 UTC, k-boikov requested changes

2023-05-16 23:48 UTC, k-boikov commented on BULLETIN.md
>  Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
Do we need those 2 paragraphs from 0.3.0? Maybe we just move the ones from bellow here.

2023-05-17 00:28 UTC, gravelBridge submitted a review, later dismissed
LGTM

2023-05-17 03:20 UTC, gravelBridge approved these changes
LGTM

2023-05-18 05:50 UTC, ntindle approved these changes

2023-05-18 05:57 UTC, ntindle approved these changes

2023-05-18 06:31 UTC, ntindle approved these changes

2023-05-18 06:31 UTC, merged