Work In Progress: OpenAI functions
Significant-Gravitas/Auto-GPT pull request #4683
Opened 2023-06-14 05:12 UTC by erik-megarad

# This is a work in progress. It's based on top of #3696, so that should be merged first.

This implements functions support for OpenAI.

This basically functions but is nowhere close to ready. Just sharing my progress.

Note: I removed a lot of commands so that I can better test things. Each command needs to have its declaration rewritten and needs to be tested to ensure that the AI will understand the commands in function form. I will add commands back as tests on them succeed.

2023-06-15 12:17 UTC, Pwuts requested changes
First of all, a million kudo's for whipping up that function support PR so quickly :D 

I am having difficulty reviewing because on top of it being a very large PR, there are a lot of seemingly out-of-scope or unexplained changes in it, e.g.:
* refactoring
* moving code around within a file
* intuitive but unexplained renaming of command arguments (=risky, needs testing)
* undoing re-arch related refactoring/restructuring
  * deprecation (but not removal) of `agent._resolve_pathlike_command_args()`

In any case, I don't agree with removing all of the non-essential commands and their implementations; see below for further explanation.

2023-06-15 12:17 UTC, Pwuts commented on autogpt/commands/file_operations.py
> +def append_to_file(
Nit: moving code around within a file doesn't help with reviewing, especially considering it's already a large PR

2023-06-15 12:17 UTC, Pwuts commented on autogpt/commands/execute_code.py
> +        name (str): A name to be given to the Python file
Have you tested this? `basename` was chosen for a reason after testing showed it could help mitigate LLM confusion.

2023-06-15 12:17 UTC, Pwuts commented on autogpt/commands/file_operations.py
> +        filename = os.path.join(agent.workspace.root, filename)
This *was* implemented centrally using `_resolve_pathlike_command_args` and `workspace.get_path()`. Why move it back into the various command implementations?

2023-06-15 12:17 UTC, Pwuts commented on autogpt/commands/image_gen.py
> I also had to disable most of the non-essential commands.
> [...]
> I couldn't do it in one go otherwise this already-massive PR would be twice as big and take four times longer.

It looks like this PR *removes* all of those commands rather than disabling them.

I don't think gutting Auto-GPT's feature set is the solution here. Removal is warranted in case of a clear indication that the function doesn't work. As of now, I have seen no such indication, and we also can't check it because the features have been removed.

For completeness: `web_playwright.py` can stay gone. It wasn't being used anyways. `audio_text.py` is also a good candidate for removal: it fits better in a plugin and I have never seen anyone using it. I'm not sure about `analyze_code.py`, `improve_code.py`, `git_operations.py`, `write_tests.py`.

2023-06-15 12:17 UTC, Pwuts commented on autogpt/agent/agent_manager.py
Disabling/removing the agent related commands is fine with me, but I'd like to keep the AgentManager so we can build/iterate on it.

2023-06-15 17:00 UTC, erik-megarad commented on autogpt/commands/image_gen.py
IMO the master code branch isn't a good place for long-term storage of dead code. I prefer to keep the current codebase effective and use git for storage of dead code.

2023-06-15 17:00 UTC, erik-megarad commented on autogpt/commands/file_operations.py
> +def append_to_file(
Fixed

2023-06-15 17:01 UTC, erik-megarad commented on autogpt/commands/file_operations.py
> +        filename = os.path.join(agent.workspace.root, filename)
For reasons that I didn't have time to investigate the AI wasn't able to work with absolute paths, it would always give relative paths. Since we want to confine things to the workspace anyways this just made a ton of sense to me.

2023-06-15 17:14 UTC, Pwuts commented on autogpt/commands/file_operations.py
> +        filename = os.path.join(agent.workspace.root, filename)
Sure, and that's what the current implementation (in `master`) does (or did, last I checked). So I'm mostly wondering why the logic is now duplicated and spread out over different implementations in multiple functions.

2023-06-15 17:17 UTC, Pwuts commented on autogpt/commands/image_gen.py
Sure, fine with me. But please undelete the rest, or we'll have barely any features left.

2023-06-16 00:23 UTC, erik-megarad commented on autogpt/commands/execute_code.py
> +        name (str): A name to be given to the Python file
Yeah, I have, it works better this way. Sometimes with basename it just left it off even thought it was required. Maybe an OpenAI bug.

2023-06-21 13:20 UTC, Pwuts requested changes
Scope reduction has made it significantly easier to review. Thanks for that @merwanehamadi and @erik-megarad!

Also, good call to make it an optional feature, since it looks like those new models really are dumber.

2023-06-21 13:20 UTC, Pwuts commented on autogpt/models/command_function.py
> +        }
This may be refactored into `dataclass`, e.g.:
```suggestion
@dataclass
class CommandFunction:
    """Represents a "function" in OpenAI, which is mapped to a Command in Auto-GPT"""

    name: str
    description: str
    parameters: dict[str, Any]
```

2023-06-21 13:20 UTC, Pwuts commented on autogpt/agent/agent.py
> +                    self.get_functions_from_commands(),
Is this necessary, since `self` is already passed?

2023-06-21 13:20 UTC, Pwuts commented on autogpt/agent/agent.py
> +        """Get functions from the commands. "functions" in this context refers to OpenAI functions
Maybe it's me, but I found this function signature to be somewhat confusing. `get_functions_from_commands` -> what functions? What is a `CommandFunction`? Turns out it is an object *representing* a command in an OpenAI-compatible format.

Some suggestions that could help understandability of the code:
* `get_functions_from_commands` -> `get_openai_command_specs`
* `CommandFunction` -> `OpenAIFunctionSpec`
  * Maybe move this model to `autogpt.llm.providers.openai`, or `autogpt.llm.base`/`autogpt.llm.models`?

Furthermore, this implements OpenAI-specific functionality that is needed for prompt generation, which doesn't belong in the `Agent` class imo.

2023-06-21 13:20 UTC, Pwuts commented on autogpt/app.py
> +        assistant_reply_json (json): The response from the AI
added parameters missing from docstring

2023-06-21 13:20 UTC, Pwuts commented on autogpt/app.py
> +    assistant_reply_json: Dict, assistant_reply: ChatCompletionResponse, config: Config
Are `assistant_reply_json` and `assistant_reply` not redundant?

2023-06-21 13:20 UTC, Pwuts commented on autogpt/llm/chat.py
> +
nit: ungrouped lines that were intentionally grouped

2023-06-21 13:20 UTC, Pwuts commented on autogpt/models/chat_completion_response.py
> +class ChatCompletionResponse:
* Could be a `dataclass`
* Partially duplicates `autogpt.llm.base.Message`
* Looking at existing project structure, this should be in `autogpt.llm.base`

2023-06-21 13:20 UTC, Pwuts commented on autogpt/models/command_argument.py
> +        self.required = required
Could be a `dataclass`, see below

2023-06-21 13:20 UTC, Pwuts commented on autogpt/processing/text.py
> +                "\n\n".joine config object
Typo?

2023-06-21 13:20 UTC, Pwuts commented on autogpt/json_utils/utilities.py
> +        json_schema["required"] = ["thoughts"]
```suggestion
        json_schema["required"].remove("command")
```

2023-06-21 13:20 UTC, Pwuts commented on autogpt/prompts/generator.py
> -            f"{self._generate_numbered_list(self.commands, item_type='command')}\n\n"
The constraints refer to "the commands listed below", so this may have unintended effects.

2023-06-21 13:20 UTC, Pwuts commented on tests/unit/test_prompt_generator.py
nice :)

2023-06-21 17:09 UTC, waynehamadi commented on autogpt/app.py
> +    assistant_reply_json: Dict, assistant_reply: ChatCompletionResponse, config: Config
the assistant_reply contains the stringified json that may or may not be convertible into json.

2023-06-21 17:52 UTC, Pwuts commented on autogpt/app.py
> +    assistant_reply_json: Dict, assistant_reply: ChatCompletionResponse, config: Config
That doesn't seem right. Do you mean `assistant_reply_json` contains a dict that may or may not be parseable as a `ChatCompletionResponse`? In that case the type hint for `assistant_reply` is probably incorrect.

2023-06-21 17:58 UTC, Pwuts commented on autogpt/app.py
> +        assistant_reply_json (json): The json response from the AI
```suggestion
        assistant_reply_json (dict): The response object from the AI
```

2023-06-21 18:15 UTC, Pwuts requested changes
Almost there :)

2023-06-21 18:15 UTC, Pwuts commented on autogpt/llm/base.py
> +    function_call: Dict[str, Any] = None
Please add a proper type for this

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/12185583/9ee1b59f-065b-41b6-880a-95fe702c66a0)

2023-06-21 18:15 UTC, Pwuts commented on autogpt/llm/base.py
> +    parameters: dict[str, Any]
Same comment as above; please add a complete type

2023-06-21 18:15 UTC, Pwuts commented on autogpt/llm/providers/openai.py
> +    """Get functions from the commands. "functions" in this context refers to OpenAI functions
```suggestion
    """Get OpenAI-consumable function specs for the agent's available commands.
```

2023-06-21 18:15 UTC, Pwuts commented on autogpt/processing/text.py
> +            prompt=summarization_prompt, config=config, temperature=0, max_tokens=500
Nit:
> - [ ] I have not snuck in any "extra" small tweaks changes.

2023-06-21 18:33 UTC, Pwuts commented on autogpt/app.py
> +                f"'assistant_reply_json' object is not dictionary {assistant_reply_json}",
nit: this will be returned to the LLM, which has no idea what `assistant_reply_json` is

2023-06-21 23:24 UTC, Pwuts commented on autogpt/prompts/generator.py
> +            f"{generate_commands(self, config)}"
Why move the commands to a different position in the prompt?

2023-06-22 02:47 UTC, Pwuts approved these changes

2023-06-22 02:52 UTC, merged