fix replace of nonetype
Significant-Gravitas/Auto-GPT pull request #4882
Opened 2023-07-04 08:37 UTC by u007

seems to be a logging issue

2023-07-04 10:12 UTC, lc0rp reviewed
Nice! Could you pair it w/ a unit test?

2023-07-04 13:54 UTC, Pwuts requested changes

2023-07-04 13:54 UTC, Pwuts commented on autogpt/logs.py
> +        return ""
This is invalid considering the type annotation of `str`. A cleaner solution would be to make sure a `str` is always passed, see below.

2023-07-04 13:54 UTC, Pwuts commented on autogpt/logs.py
> +        remove_ansi_escape(assistant_thoughts.get("text"))
```suggestion
        remove_ansi_escape(assistant_thoughts.get("text", ""))
```

2023-07-06 19:31 UTC, Pwuts approved these changes

2023-07-06 23:15 UTC, Pwuts commented
Note that this PR doesn't fix the instance reported in #4845:

      File "C:\Users\Zachary\Documents\Personal_Projects\autogpt\auto-gpt_git\Auto-GPT\autogpt\agent\agent.py", line 188, in start_interaction_loop
        f"COMMAND = {Fore.CYAN}{remove_ansi_escape(command_name)}{Style.RESET_ALL}  "
      File "C:\Users\Zachary\Documents\Personal_Projects\autogpt\auto-gpt_git\Auto-GPT\autogpt\logs.py", line 253, in remove_ansi_escape
        return s.replace("\x1B", "") AttributeError: 'NoneType' object has no attribute 'replace'

2023-07-07 00:00 UTC, merged