Fix possible timeout to OpenAI crashing Auto-GPT.
Significant-Gravitas/Auto-GPT pull request #556
Opened 2023-04-09 05:17 UTC by BillSchumacher

### Background

![image](https://user-images.githubusercontent.com/34168009/230755671-ddc951c8-3566-4426-8587-35a74d7f3186.png)

It's possible for your connection being closed causes AutoGPT to crash.

### Changes

Wraps the embeddings call with a try statement and returns an empty list when finding nearest or avoids adding to memory.

### Test Plan

It's not tested, one could disable their internet connection to test.

### Change Safety

- [ ] I have added tests to cover my changes
- [x] I have considered potential risks and mitigations for my changes

2023-04-09 06:17 UTC, richbeales approved these changes
This looks good

2023-04-09 06:30 UTC, Torantulino requested changes

2023-04-09 06:30 UTC, Torantulino commented on scripts/memory/base.py
> +        print("Error getting embedding: ", e)
We could do with returning something to the AI here to let them know their command didn't work and that they should try again.

2023-04-16 10:13 UTC, DdondD commented
wow 💯

2023-04-29 17:04 UTC, closed without merging