Clarity on fork & clone instructions
Significant-Gravitas/Auto-GPT pull request #589
Opened 2023-04-09 12:54 UTC by aosan

### Background

### Changes

### Test Plan

### Change Safety

- [ ] I have added tests to cover my changes
- [ ] I have considered potential risks and mitigations for my changes

2023-04-09 13:06 UTC, nponeccop approved these changes

2023-04-09 14:35 UTC, richbeales approved these changes

2023-04-09 15:00 UTC, suensummit requested changes
Still lack the step to add remote upstream, maybe you could add that as well?

2023-05-04 22:46 UTC, p-i- approved these changes

2023-05-04 22:47 UTC, closed without merging

2023-05-04 22:53 UTC, anonhostpi commented
![image](https://user-images.githubusercontent.com/130698314/236345814-3eae2c3f-a5ce-42a1-87ed-75f3c1214c8e.png)
![image](https://user-images.githubusercontent.com/130698314/236346212-b166d42c-dde8-41fd-9cd7-148b81f0024f.png)

@p-i-