Few refactoring to follow pep_8 conventions, dict map in get_command in commands.py and requirements updated
Significant-Gravitas/Auto-GPT pull request #602
Opened 2023-04-09 15:44 UTC by Flintpop

### Background

I found few things that could be rapidly refactored, like the endless elif statements in commands.py and the few blanks lacking in the project.

### Changes

Many blanks added, few types added in function prototypes to improve debugging, added a dictionary to remove all the elif in commands.py, and added few constants.
The requirements has been automatically updated by Pycharm. Some verifications may be needed.

### Test Plan

No tests.

### Change Safety

- [ ] I have added tests to cover my changes
- [x] I have considered potential risks and mitigations for my changes

There is no tests added but there should be no breaking changes.

2023-04-09 18:19 UTC, richbeales commented
Probably a good PR, but mass refactorings like this are difficult to follow, and may be better being pulled apart into separate atomic PRs to address different issues.

2023-04-09 19:55 UTC, norregaarden approved these changes

2023-04-10 06:49 UTC, nponeccop requested changes
I suggest just to focus on moving the imports around (and isort compliance).

2023-04-10 06:49 UTC, nponeccop commented on requirements.txt
Make the pinning down a separate PR

2023-04-10 06:49 UTC, nponeccop commented on scripts/agent_manager.py
> +
An unnecessary whitespace change

2023-04-10 06:49 UTC, nponeccop commented on scripts/ai_config.py
> +import os
Unnecessary move of imports

2023-04-10 06:49 UTC, nponeccop commented on scripts/ai_config.py
> +            full_prompt += f"{i + 1}. {goal}\n"
This is good but submit whitespace changes apart.

2023-04-10 06:49 UTC, nponeccop commented on scripts/config.py
> +
Why these spaces?

2023-04-10 06:49 UTC, nponeccop commented on scripts/config.py
> -
This change is actually in #590 already

2023-04-24 06:23 UTC, closed without merging