Update token_counter.py - Low priority error message change
Significant-Gravitas/Auto-GPT pull request #691
Opened 2023-04-10 13:25 UTC by phoebebright

Add additional clarification to error message as this is the first check of the model name.  An alternative approach would be to add a verification of the model before this is called.

### Background

### Changes

### Documentation

### Test Plan

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thouroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-04-10 15:41 UTC, nponeccop requested changes

2023-04-10 15:41 UTC, nponeccop commented on scripts/token_counter.py
> +        raise NotImplementedError(f"""model {model} is not a reconised model or num_tokens_from_messages() is not implemented for model {model}. See https://github.com/openai/openai-python/blob/main/
reconised is a typo, g is missing

2023-04-10 17:54 UTC, blankster approved these changes

2023-05-05 00:57 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-06-14 22:36 UTC, Pwuts commented
Closing this PR as it is outdated and there was no response to maintainer review

2023-06-14 22:36 UTC, closed without merging