Use Python 3 Pathlib standards, increased error handling
Significant-Gravitas/Auto-GPT pull request #85
Opened 2023-04-03 16:31 UTC by yousefissa

This PR focuses on enhancing the file operations module by implementing the following changes:

* Replacing the `os` and `os.path` modules with the `pathlib module`, which simplifies file and directory operations while providing better readability.
* Improving exception handling by using specific exceptions (e.g., FileNotFoundError) instead of generic exceptions where appropriate. This change enables more informative error messages to be returned to the user.
* Updating error message formatting by using f-strings, which enhances readability and consistency.

These updates contribute to a more robust and maintainable file operations module, making it easier to understand and modify in the future.

2023-04-09 10:20 UTC, nponeccop requested changes
Rebase against the current master.

2023-04-20 17:12 UTC, AndresCdo commented on scripts/constants.py
> +
Unnecessary file.

2023-04-20 17:13 UTC, AndresCdo commented on scripts/execute_code.py
> +from docker import errors
Changes not related with PR description.

2023-04-20 17:13 UTC, AndresCdo commented on scripts/execute_code.py
> +    workspace_folder = WORKSPACE_DIR
Changes not related with PR description.

2023-04-20 17:14 UTC, AndresCdo commented on scripts/execute_code.py
> +    except docker.errors.APIError as e:
Changes not related with PR description.

2023-05-05 00:56 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-07-07 05:18 UTC, Pwuts commented
An open draft PR from 3 April, oof...

This PR is too far out of date to be fixed up or merged. Since it's also a draft, I don't feel too bad closing it. Still, please feel welcome to join our dev sessions on Discord and to contribute again in the future. :)

2023-07-07 05:18 UTC, closed without merging