Added create_directory, create_directories, list_files, create_files, search sent emails in Outlook
Significant-Gravitas/Auto-GPT pull request #940
Opened 2023-04-12 10:50 UTC by CraigWhiteART

2023-04-12 11:14 UTC, nponeccop requested changes

2023-04-12 11:14 UTC, nponeccop commented on tests/test_email_search.py
> +search_sent_emails("welcome")
These file endings are against pep8. Change accordingly by ensuring that you don't occasionally delete the final newline.

2023-04-12 11:14 UTC, nponeccop commented on scripts/commands.py
> -
Rollback the whiteline corrections. We'll do them in a separate PR (which is already there, just not merged yet)

2023-05-05 00:56 UTC, p-i- commented
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

2023-06-14 22:26 UTC, Pwuts commented
* Outlook-related functionality could be in a plugin (or maybe it already is?
* Other added commands aren't necessary with the current set of commands available in `master`

Closing this PR, thanks for submitting though!

2023-06-14 22:26 UTC, closed without merging